const router = require("express").Router()
const {addExam, getAllExams, getExamById, editExam, deleteExam, addQuestionToExam, deleteQuestionFromExam, editQuestionInExam, saveTestProgress, getCandidateCrm, getAllExamsByUser, addTrackLink, deleteTrackLink, changeStatus, ModificaExam, updateCandidatePreference, updateCandidateNotes, addExamMix, saveTestProgressMix} = require("../controllers/examControllers")
const authMiddleware = require("../middlewares/authMiddleware")

router.post('/addExam',authMiddleware,addExam)
router.post('/addExamMix',authMiddleware,addExamMix)
router.get('/getAllExams',authMiddleware,getAllExams)
router.get('/getAllExamsByUser/:id',getAllExamsByUser)
router.get('/getExamById/:id',getExamById)
router.get('/getCandidateCrm/:id', authMiddleware,getCandidateCrm)
router.put('/editExam/:id',authMiddleware,editExam)
router.delete('/deleteExam/:id',authMiddleware,deleteExam)
router.post('/addQuestionToExam/:id',authMiddleware,addQuestionToExam)
router.delete('/deleteQuestionFromExam/:id',authMiddleware,deleteQuestionFromExam)
router.put('/editQuestionInExam/:id',authMiddleware,editQuestionInExam)
router.put('/save-test-progress', saveTestProgress)
router.put('/save-test-progress-mix', saveTestProgressMix)
router.post('/addTrackLink',authMiddleware,addTrackLink)
router.post('/deleteTrackLink',authMiddleware,deleteTrackLink)
router.post('/changeStatusExam',authMiddleware,changeStatus)
router.post('/modificaExam',authMiddleware,ModificaExam)
router.post('/updateCandidatePref',authMiddleware,updateCandidatePreference)
router.post('/updateCandidateNotes',authMiddleware,updateCandidateNotes)

module.exports = router;